### ISSUE TITLE
orderBy / thenBy does not properly apply the correct order

### ISSUE THREAD

**Issue by tonyxiao** [data-forge/data-forge-ts#88]
```ts
const data = [
    {'account.name': 'Cash'},
    {'account.name': 'Investments/IRA'},
    {'account.name': 'Cash', date: '2020-01-01'},
    {'account.name': 'Cash', date: '2020-01-01', memo: 'orange'},
    {'account.name': 'Investments', date: '2020-01-01'},
    {'account.name': 'Investments'},
    {'account.name': 'Cash', date: '2020-01-01', memo: 'apple'},
    {'account.name': 'Investments', date: '2020-01-01', memo: 'apple'},
    {'account.name': 'Investments', date: '2020-01-01', memo: 'orange'},
    {'account.name': 'Investments/IRA', date: '2020-01-01', memo: 'apple'},
    {'account.name': 'Investments/IRA', date: '2020-01-01'},
    {'account.name': 'Investments/IRA', date: '2020-01-01', memo: 'orange'},
    {'account.name': 'Cash', date: '2020-02-01', memo: 'apple'},
    {'account.name': 'Cash', date: '2020-02-01'},
    {'account.name': 'Cash', date: '2020-02-01', memo: 'orange'},
    {'account.name': 'Investments', date: '2020-02-01', memo: 'apple'},
    {'account.name': 'Investments', date: '2020-02-01', memo: 'orange'},
    {'account.name': 'Investments', date: '2020-02-01'},
    {'account.name': 'Investments/IRA', date: '2020-02-01'},
    {'account.name': 'Investments/IRA', date: '2020-02-01', memo: 'apple'},
    {'account.name': 'Investments/IRA', date: '2020-02-01', memo: 'orange'},
  ]
  console.log(
    new Series(data)
      .orderBy((r) => r['account.name'])
      .thenBy((r) => r.date)
      .thenBy((r) => r.memo)
      .toArray(),
  )
```

This will output the following
```ts
[
    {'account.name': 'Cash'},
    {'account.name': 'Investments/IRA'},
    {'account.name': 'Cash', date: '2020-01-01'},
    {'account.name': 'Investments'},
    {'account.name': 'Cash', date: '2020-01-01', memo: 'apple'},
    {'account.name': 'Cash', date: '2020-01-01', memo: 'orange'},
    {'account.name': 'Investments', date: '2020-01-01'},
    {'account.name': 'Investments', date: '2020-01-01', memo: 'apple'},
    {'account.name': 'Investments', date: '2020-01-01', memo: 'orange'},
    {'account.name': 'Investments/IRA', date: '2020-01-01', memo: 'apple'},
    {'account.name': 'Investments/IRA', date: '2020-01-01', memo: 'orange'},
    {'account.name': 'Investments/IRA', date: '2020-01-01'},
    {'account.name': 'Cash', date: '2020-02-01', memo: 'apple'},
    {'account.name': 'Cash', date: '2020-02-01'},
    {'account.name': 'Cash', date: '2020-02-01', memo: 'orange'},
    {'account.name': 'Investments', date: '2020-02-01', memo: 'apple'},
    {'account.name': 'Investments', date: '2020-02-01', memo: 'orange'},
    {'account.name': 'Investments', date: '2020-02-01'},
    {'account.name': 'Investments/IRA', date: '2020-02-01'},
    {'account.name': 'Investments/IRA', date: '2020-02-01', memo: 'apple'},
    {'account.name': 'Investments/IRA', date: '2020-02-01', memo: 'orange'},
  ]
```
Which is super unexpected.

**Comment by ashleydavis** [comment]
Ok there's potentially a problem with your code here.

1. This looks like tabular data so you probably want to use a `DataFrame` instead of a `Series`.
2. You columns are irregular so you'll need to constructor your `DataFrame` with the `considerAllRows` option enabled. This makes it slower because it will look at all rows to determine the columns of the data frame. If you want it fast you could use the `columnNames` field to explicitly set the columns that you know are in the data.
3. To sort dates effectively you probably need to parse the strings to dates using the `parseDates` function.

Here's the updated code:

```javascript
    new DataFrame({ values: data, considerAllRows: true })
        .parseDates("date", "YYYY-MM-D")
        .orderBy((r) => r['account.name'])
        .thenBy((r) => r.date)
        .thenBy((r) => r.memo)
```

Here's the output displayed in Data-Forge Notebook:

![dfn output](https://user-images.githubusercontent.com/625126/91794432-5ed01e80-ec5e-11ea-9086-4c8cfc646b5b.png)

Please let me know if this looks more like what you were expecting.

**Comment by ashleydavis** [comment]
Now that I'm thinking about it both `DataFrame` and `Series` should work the same way in this regard (except you can parseDates in the same way on a `Series`).

Looking at the code there is a discrepancy between them. I wonder if that would account for this issue.

**Comment by ashleydavis** [comment]
Ok, I think I have corrected the original problem by updating the code for `Series` from `DataFrame` to remove the discrepency.

This is the output now using your original code example:

![image](https://user-images.githubusercontent.com/625126/91795216-698bb300-ec60-11ea-924b-0b1c580bd698.png)

This is published in version 1.8.11 of Data-Forge.

Let me know if it works as you expect.

**Comment by tonyxiao** [comment]
Interesting. as of version `1.8.9`,  using `DataFrame` returns the following (regardless of `considerAllRows` produces the following) but using `Series` does not. (returns results in the OP)

```
[
  {'account.name': 'Cash'},
  {'account.name': 'Cash', date: '2020-01-01', memo: 'apple'},
  {'account.name': 'Cash', date: '2020-01-01'},
  {'account.name': 'Cash', date: '2020-01-01', memo: 'orange'},
  {'account.name': 'Cash', date: '2020-02-01'},
  {'account.name': 'Cash', date: '2020-02-01', memo: 'apple'},
  {'account.name': 'Cash', date: '2020-02-01', memo: 'orange'},
  {'account.name': 'Investments', date: '2020-01-01', memo: 'apple'},
  {'account.name': 'Investments', date: '2020-02-01', memo: 'apple'},
  {'account.name': 'Investments', date: '2020-02-01', memo: 'orange'},
  {'account.name': 'Investments'},
  {'account.name': 'Investments', date: '2020-01-01'},
  {'account.name': 'Investments', date: '2020-01-01', memo: 'orange'},
  {'account.name': 'Investments', date: '2020-02-01'},
  {'account.name': 'Investments/IRA', date: '2020-01-01', memo: 'orange'},
  {'account.name': 'Investments/IRA'},
  {'account.name': 'Investments/IRA', date: '2020-01-01', memo: 'apple'},
  {'account.name': 'Investments/IRA', date: '2020-01-01'},
  {'account.name': 'Investments/IRA', date: '2020-02-01'},
  {'account.name': 'Investments/IRA', date: '2020-02-01', memo: 'apple'},
  {'account.name': 'Investments/IRA', date: '2020-02-01', memo: 'orange'},
]
```

However, this is still unexpected though, I'd expect the following

```
[
  {'account.name': 'Cash', date: '2020-01-01', memo: 'apple'},
  {'account.name': 'Cash', date: '2020-01-01', memo: 'orange'},
  {'account.name': 'Cash', date: '2020-01-01'},
  {'account.name': 'Cash', date: '2020-02-01', memo: 'apple'},
  {'account.name': 'Cash', date: '2020-02-01', memo: 'orange'},
  {'account.name': 'Cash', date: '2020-02-01'},
  {'account.name': 'Cash'},
  {'account.name': 'Investments', date: '2020-01-01', memo: 'apple'},
  {'account.name': 'Investments', date: '2020-01-01', memo: 'orange'},
  {'account.name': 'Investments', date: '2020-01-01'},
  {'account.name': 'Investments', date: '2020-02-01', memo: 'apple'},
  {'account.name': 'Investments', date: '2020-02-01', memo: 'orange'},
  {'account.name': 'Investments', date: '2020-02-01'},
  {'account.name': 'Investments'},
  {'account.name': 'Investments/IRA', date: '2020-01-01', memo: 'apple'},
  {'account.name': 'Investments/IRA', date: '2020-01-01', memo: 'orange'},
  {'account.name': 'Investments/IRA', date: '2020-01-01'},
  {'account.name': 'Investments/IRA', date: '2020-02-01', memo: 'apple'},
  {'account.name': 'Investments/IRA', date: '2020-02-01', memo: 'orange'},
  {'account.name': 'Investments/IRA', date: '2020-02-01'},
  {'account.name': 'Investments/IRA'},
]
```

Gonna test out 1.8.11 now

**Comment by tonyxiao** [comment]
Update. in 1.8.11 Series produces the same result as `DataFrame`, however it's still not the result that I would expect. 

Side question: I tend to default to using Series unless something requires the use of DataFrame. Never expected there to be behavioral differences between them for functions that have otherwise identical signature. Is there a different strategy I should be using?

**Comment by tonyxiao** [comment]
Somewhat related question - is there a version of orderBy that takes comparator function which I missed?

**Comment by ashleydavis** [comment]
Sorry... just catching up.

1. Why do you expect null values to come first? Is that a convention I don't know about?

2. It's ok to use DataFrame or Series however you want. In fact, I'm glad you used Series and discovered that it didn't work the same as DataFrame for the orderBy function.

3. There is no version of orderBy that takes a comparator. I'd be happy for you to implement that as an optional extra. If you are interested in adding it, pls let me know and I'll tell what's required to get your PR accepted.

**Comment by ashleydavis** [comment]
Closing due to no activity. If this is still a problem that needs to be fixed please reopen this issue.
